version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8084:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 