name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v9
      with:
        uploadArtifacts: true
        temporaryPublicStorage: false
        configPath: './lighthouserc.js'
        artifactName: lighthouse-results
    
    - name: Check HTML validity
      run: |
        npm install -g html-validate
        html-validate index.html
    
    - name: Check CSS validity
      run: |
        npm install -g css-validator
        css-validator styles.css
    
    - name: Check for broken links
      run: |
        npm install -g broken-link-checker
        blc http://localhost:8085 -ro
    
    - name: Check for accessibility issues
      run: |
        npm install -g axe-cli
        axe http://localhost:8085
    
    - name: Check for security issues
      run: |
        npm install -g snyk
        snyk test 